### ISSUE TITLE
Provide support for PHP 7.2

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-xml2json#7]
We need to require that PHP 7.2 tests pass (currently allows failure).

**Comment by hkulekci** [comment]
@weierophinney  there is a mixed return type problem on https://github.com/zendframework/zend-xml2json/blob/master/src/Xml2Json.php#L78 I will send a PR but it will be BC break. What do you think?

**Comment by hkulekci** [comment]
And also phpunit result is successfull on php 7.2.4.

**Comment by weierophinney** [comment]
> there is a mixed return type problem on https://github.com/zendframework/zend-xml2json/blob/master/src/Xml2Json.php#L78

I'm sorry - what is the problem? Is it with the caller, in terms of not handling the two variants?
